### ISSUE TITLE
Not able to add the ppa in Ubuntu 16.04

### ISSUE THREAD

**Issue by rohan-paul** [gerardpuig/ubuntu-cleaner#14]
After running `sudo add-apt-repository ppa:gerardpuig/ppa`  getting the below

```
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 98, in <module>
    main()
  File "/usr/bin/lsb_release", line 62, in main
    distinfo = lsb_release.get_distro_information(options.upstream)
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 386, in get_distro_information
    distinfo = guess_debian_release()
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 281, in guess_debian_release
    get_distro_info(distinfo['ID'])
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 41, in get_distro_info
    RELEASES_ORDER.sort(key=lambda n: float(n[0]))
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 41, in <lambda>
    RELEASES_ORDER.sort(key=lambda n: float(n[0]))
ValueError: could not convert string to float: '16.04 LTS'
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 98, in <module>
    main()
  File "/usr/bin/lsb_release", line 62, in main
    distinfo = lsb_release.get_distro_information(options.upstream)
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 386, in get_distro_information
    distinfo = guess_debian_release()
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 281, in guess_debian_release
    get_distro_info(distinfo['ID'])
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 41, in get_distro_info
    RELEASES_ORDER.sort(key=lambda n: float(n[0]))
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 41, in <lambda>
    RELEASES_ORDER.sort(key=lambda n: float(n[0]))
ValueError: could not convert string to float: '18.04 LTS'
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 98, in <module>
    main()
  File "/usr/bin/lsb_release", line 62, in main
    distinfo = lsb_release.get_distro_information(options.upstream)
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 386, in get_distro_information
    distinfo = guess_debian_release()
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 281, in guess_debian_release
    get_distro_info(distinfo['ID'])
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 41, in get_distro_info
    RELEASES_ORDER.sort(key=lambda n: float(n[0]))
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 41, in <lambda>
    RELEASES_ORDER.sort(key=lambda n: float(n[0]))
ValueError: could not convert string to float: '6.06 LTS'
 Official Ubuntu Cleaner stable repository
 More info: https://launchpad.net/~gerardpuig/+archive/ubuntu/ppa
Press [ENTER] to continue or ctrl-c to cancel adding it
```

**Comment by gerardpuig** [comment]
Hi, this is not an issue of this application per se, you are having an issue with `add-apt-repository` command.
Instead you can always do it manually so for the xenial release create file:
`/etc/apt/sources.list.d/gerardpuig-ubuntu-ppa-xenial.list`

With content
`deb http://ppa.launchpad.net/gerardpuig/ppa/ubuntu xenial main`
