### ISSUE TITLE
Cleaning package configs fails

### ISSUE THREAD

**Issue by jgmGit** [gerardpuig/ubuntu-cleaner#39]
I am using ubuntu 20.04 and trying to clean the old package config fails with the error.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/ubuntucleaner/janitor/packageconfigs_plugin.py", line 57, in clean_cruft
    line, returncode = proxy.get_cmd_pipe()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/ubuntucleaner/daemon/service.py", line 65, in get_cmd_pipe
    strings, returncode = ''.join(self.p.stdout.readlines()), str(terminaled)
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by gerardpuig** [comment]
Hi @jgmGit same issue as #37
