### ISSUE TITLE
Ubuntu Cleaner crashed when selecting Personal item on Ubuntu 20

### ISSUE THREAD

**Issue by JuraLys** [gerardpuig/ubuntu-cleaner#55]
see attached screenshot
![Ubuntu-cleaner-crash(](https://github.com/gerardpuig/ubuntu-cleaner/assets/146434286/aaf3c857-9c1f-456f-8508-723413932230)

**Comment by gerardpuig** [comment]
thanks for reporting, could you open the app from the command line and give me more details on the crash? maybe it's because you have too many files, thanks!

**Comment by JuraLys** [comment]
> thanks for reporting, could you open the app from the command line and give me more details on the crash? maybe it's because you have too many files, thanks!

please write which command should I enter?
ubuntucleaner: command not found

**Comment by JuraLys** [comment]
> thanks for reporting, could you open the app from the command line and give me more details on the crash? maybe it's because you have too many files, thanks!

ptsg@ptsgVM20:~$ sudo ubuntu-cleaner
/usr/lib/python3/dist-packages/ubuntucleaner/settings/debug.py:7: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Gdk, Gtk, Notify
/usr/bin/ubuntu-cleaner:70: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
/usr/bin/ubuntu-cleaner:71: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ubuntucleaner/janitor/__init__.py", line 447, in on_janitor_check_button_toggled
    self._auto_scan_cruft(iter, checked)
  File "/usr/lib/python3/dist-packages/ubuntucleaner/janitor/__init__.py", line 538, in _auto_scan_cruft
    self.do_scan_task()
  File "/usr/lib/python3/dist-packages/ubuntucleaner/janitor/__init__.py", line 544, in do_scan_task
    plugin.set_property('scan_finished', False)
AttributeError: 'NoneType' object has no attribute 'set_property'

**Comment by gerardpuig** [comment]
thanks! that helps for the investigation. I'll try to reproduce it locally and fix it in the new version when I have some time for it
