### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by jefro108** [gerardpuig/ubuntu-cleaner#57]
I get the following error when starting in the cli

`Traceback (most recent call last):
  File "/usr/bin/ubuntu-cleaner", line 18, in <module>
    from ubuntucleaner.settings.debug import enable_debugging
  File "/usr/lib/python3/dist-packages/ubuntucleaner/settings/debug.py", line 7, in <module>
    from gi.repository import Gdk, Gtk, Notify
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 136, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name Notify, introspection typelib not found
`

I see there was a similar error in version 1.1.1  - see https://github.com/gerardpuig/ubuntu-cleaner/issues/33 which was fixed in version  1.1.2

On Ubuntu 22.04

**Comment by gerardpuig** [comment]
Could you install gir1.2-notify-0.7 ? 

So `sudo apt install gir1.2-notify-0.7` that should resolve your issue
