### ISSUE TITLE
Ubuntu Cleaner crashed when selecting Personal item - Ubuntu 24.04

### ISSUE THREAD

**Issue by Max-1960** [gerardpuig/ubuntu-cleaner#58]
I work on Ubuntu 24.04 and Ubuntu Cleaner 1.1.4 .

I installed Ubuntu Cleaner with this command:
sudo add-apt-repository ppa:gerardpuig/ppa -y
	sudo apt update
	sudo apt install ubuntu-cleaner

Every time I activate Ubuntu-Cleaner it crashes and doesn't allow me to use any functions. What can I do ?

Thanks

**Comment by gerardpuig** [comment]
could you execute it from the terminal and paste the output? thanks

**Comment by Max-1960** [comment]
Thank you for your response.
What is the exact command to execute in terminal? Are there any particular options I could write?

In any case I suppose that after the command the menu appears in graphical form and everything stops there.

But it is correct to follow your advice.

**Comment by Max-1960** [comment]
I execute this cmd from the: ubuntu-cleaner

This is output:

/usr/lib/python3/dist-packages/ubuntucleaner/settings/debug.py:7: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Gdk, Gtk, Notify
/usr/bin/ubuntu-cleaner:70: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
/usr/bin/ubuntu-cleaner:71: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
[ModuleLoader][ERROR] Module import error: No module named 'distutils' (__init__.py:67)

Then the "Computer Janitor" screen appears and I can't mark any options.

Then close the windows of the "Computer Janitor" and appears on terminal:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ubuntucleaner/janitor/__init__.py", line 447, in on_janitor_check_button_toggled
    self._auto_scan_cruft(iter, checked)
  File "/usr/lib/python3/dist-packages/ubuntucleaner/janitor/__init__.py", line 538, in _auto_scan_cruft
    self.do_scan_task()
  File "/usr/lib/python3/dist-packages/ubuntucleaner/janitor/__init__.py", line 544, in do_scan_task
    plugin.set_property('scan_finished', False)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_property'

What can I do ?

Thanks

**Comment by gerardpuig** [comment]
Ah I see, this package got deprecated in python3.12 which is the version that runs by default in Ubuntu 24.04
Could you install the following package?

`apt install python3-distutils-extra`

After that it should work fine

**Comment by Max-1960** [comment]
I Have installed python3-distutils-extra .
Now ubuntu cleaner start up without error,  However, when I open the window, I cannot select the various options.
I have to insist several times with the various keys or close and start the task again, to finally be able to use it.

I am an old user of Ubuntu Cleaner and on Ubuntu 18.04 everything was very smooth and without any problems.

Can you help me ?

massimo@thinkpad-x201:~$ ubuntu-cleaner
/usr/lib/python3/dist-packages/ubuntucleaner/settings/debug.py:7: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Gdk, Gtk, Notify
/usr/bin/ubuntu-cleaner:70: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
/usr/bin/ubuntu-cleaner:71: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ubuntucleaner/janitor/__init__.py", line 447, in on_janitor_check_button_toggled
    self._auto_scan_cruft(iter, checked)
  File "/usr/lib/python3/dist-packages/ubuntucleaner/janitor/__init__.py", line 538, in _auto_scan_cruft
    self.do_scan_task()
  File "/usr/lib/python3/dist-packages/ubuntucleaner/janitor/__init__.py", line 544, in do_scan_task
    plugin.set_property('scan_finished', False)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_property'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ubuntucleaner/janitor/__init__.py", line 447, in on_janitor_check_button_toggled
    self._auto_scan_cruft(iter, checked)
  File "/usr/lib/python3/dist-packages/ubuntucleaner/janitor/__init__.py", line 538, in _auto_scan_cruft
    self.do_scan_task()
  File "/usr/lib/python3/dist-packages/ubuntucleaner/janitor/__init__.py", line 544, in do_scan_task
    plugin.set_property('scan_finished', False)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_property'

**Comment by gerardpuig** [comment]
Hi, it is weird that works randomly...I will have to test it thoroughly with ubuntu 24.04, with new python version it may require some adjustments

**Comment by Max-1960** [comment]
Thanks for the time you dedicated to me. I'm waiting for a new version of 'ubuntu cleaner'. Okay? It's a great application for all Ubuntu users ! Good work and thanks again

**Comment by Max-1960** [comment]
Dear Gerard Puig, when is a new version for Ubuntu-Cleaner expected ? On Ubuntu 24.04 current usage is still too inconsistent. It's a really useful software and I would like to use it again to 
100%. Thank you !!
